# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_lugares_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='ciudades',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='galerias',
            options={'verbose_name_plural': 'Galerias'},
        ),
        migrations.AlterModelOptions(
            name='lugares',
            options={'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='perfiles',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='permisos',
            options={'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name_plural': 'Ranking'},
        ),
        migrations.AlterModelOptions(
            name='redessociales',
            options={'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rutas',
            options={'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterModelOptions(
            name='telefonos',
            options={'verbose_name_plural': 'Telefonos'},
        ),
        migrations.AddField(
            model_name='coordenadas',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Lugares'),
        ),
    ]
