# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20161019_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenadas',
            options={'verbose_name_plural': 'Coordenadas'},
        ),
        migrations.AlterField(
            model_name='telefonos',
            name='valor',
            field=models.IntegerField(max_length=20),
        ),
    ]
