# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20161019_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugares',
            name='rutas',
        ),
        migrations.AddField(
            model_name='rutas',
            name='lugares',
            field=models.ManyToManyField(to='backend.Lugares'),
        ),
        migrations.AlterField(
            model_name='telefonos',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
